"""add provider identity to jobs

Revision ID: 0bd32dc60608
Revises: a65dc10da827
Create Date: 2026-07-11 17:35:35.317222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd32dc60608'
down_revision: Union[str, Sequence[str], None] = 'a65dc10da827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('jobs', sa.Column('provider_job_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint('uq_provider_job', 'jobs', ['provider', 'provider_job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_provider_job', 'jobs', type_='unique')
    op.drop_column('jobs', 'provider_job_id')
    op.drop_column('jobs', 'provider')
    # ### end Alembic commands ###
