"""add parsed_data to resumes

Revision ID: 2c25fe639bc2
Revises: a0053f3d47ae
Create Date: 2026-07-13 14:20:47.157039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c25fe639bc2'
down_revision: Union[str, Sequence[str], None] = 'a0053f3d47ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsed_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parsed_data')
    # ### end Alembic commands ###
