"""add raw text to resumes

Revision ID: 8c5a949a3424
Revises: a1bbdc1d1e4d
Create Date: 2026-07-12 17:54:58.470710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5a949a3424'
down_revision: Union[str, Sequence[str], None] = 'a1bbdc1d1e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'raw_text')
    # ### end Alembic commands ###
