"""add extended job fields

Revision ID: a0053f3d47ae
Revises: 8c5a949a3424
Create Date: 2026-07-12 21:11:21.211210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0053f3d47ae'
down_revision: Union[str, Sequence[str], None] = '8c5a949a3424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('responsibilities', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('team', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('benefits', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'benefits')
    op.drop_column('jobs', 'team')
    op.drop_column('jobs', 'department')
    op.drop_column('jobs', 'responsibilities')
    op.drop_column('jobs', 'requirements')
    # ### end Alembic commands ###
