"""remove source column from jobs

Revision ID: c94b2e77aa29
Revises: 0bd32dc60608
Create Date: 2026-07-11 19:04:03.755744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94b2e77aa29'
down_revision: Union[str, Sequence[str], None] = '0bd32dc60608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
